[package]
name = "validjson"
version = "0.1.0"
authors = ["Mezner <mezner@russellmyers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
valico = "3.1.0"
structopt = "0.3"
serde_json = "1.0"